### ISSUE TITLE
AttributeError: 'YamlParser' object has no attribute 'REID_CKPT

### ISSUE THREAD

**Issue by VYRION-Ai** [thangphung215/Vehicle_detection_tracking_speed_estimation_front_view#1]
```
Traceback (most recent call last):
  File "track.py", line 508, in <module>
    detect(args)
  File "track.py", line 171, in detect
    deepsort = DeepSort(cfg.DEEPSORT.REID_CKPT,
AttributeError: 'YamlParser' object has no attribute 'REID_CKPT
```

**Comment by VYRION-Ai** [comment]
if i delete the 
` cfg.DEEPSORT.REID_CKPT,`
i still got an other error 


```
Traceback (most recent call last):
  File "track.py", line 507, in <module>
    detect(args)
  File "track.py", line 171, in detect
    deepsort = DeepSort(max_dist=cfg.DEEPSORT.MAX_DIST, min_confidence=cfg.DEEPSORT.MIN_CONFIDENCE,
AttributeError: 'YamlParser' object has no attribute 'MIN_CONFIDENCE'
```


and also can you update the repo with new yolov5  repo files and deepsort repo also(as there are allote of changes )

**Comment by thangphung215** [comment]
> ```
> Traceback (most recent call last):
>   File "track.py", line 508, in <module>
>     detect(args)
>   File "track.py", line 171, in detect
>     deepsort = DeepSort(cfg.DEEPSORT.REID_CKPT,
> AttributeError: 'YamlParser' object has no attribute 'REID_CKPT
> ```

I have just fixed the bug with the updated repo with yolov5 and deep sort. Please try again. Thank you so much

**Comment by totoadel** [comment]
> I have just fixed the bug with the updated repo with yolov5 and deep sort. Please try again. Thank you so much

sorry but where is the other files, like requirements.txt , (yolov5 and deep sort i download them ok

**Comment by VYRION-Ai** [comment]
i got this error
`Fusing layers...
Model Summary: 213 layers, 7225885 parameters, 0 gradients
video 1/1 (1/1190) E:\Python\Car_Project\Vehicle_detection_tracking_speed_estimation_front_view-main\Vehicle_detection_tracking_speed_estimation_front_view-main\cars.mp4: 736x1280 1 person, 5 cars, 1 truck, Done. YOLO:(0.052s), DeepSort:(0.112s)
video 1/1 (2/1190) E:\Python\Car_Project\Vehicle_detection_tracking_speed_estimation_front_view-main\Vehicle_detection_tracking_speed_estimation_front_view-main\cars.mp4: 736x1280 1 person, 5 cars, Done. YOLO:(0.048s), DeepSort:(0.072s)
Traceback (most recent call last):
  File "track_4.py", line 382, in <module>
    detect(opt)
  File "track_4.py", line 289, in detect
    annotator.box_label(bboxes, label, color=colors(c, True),speed = speed[str(output[-2])][6])
TypeError: box_label() got an unexpected keyword argument 'speed'`

**Comment by VYRION-Ai** [comment]
Speed is always zero , there are no speed detected ,

**Comment by thangphung215** [comment]
Oh I am so sorry. I also edited the file inside annotator.box_label function. I will update soon

**Comment by VYRION-Ai** [comment]
I am sorry , but please can you send updates today, as i need it very necessary, thank you

**Comment by thangphung215** [comment]
I have updated. Please move that plot.py to yolov5/utils/

**Comment by VYRION-Ai** [comment]
Thank you very much.
the code runs , but no video saved , i use this code order
`python track_4.py --source cars.mp4 --kph .other_tools\hsv_thresh.py --save-vid --yolo_model yolov5s.pt --imgsz 640 --show-vid`
 it runs , and told me 
`Speed: 0.8ms pre-process, 19.4ms inference, 3.4ms NMS, 71.4ms deep sort update         per image at shape (1, 3, 640, 640)
Results saved to runs\track\exp2\cars.mp4`

but the video didn't saved , i cannot find it




another thing please , 
`    parser.add_argument('--p1',type=int, default=537,help='limitation')
    parser.add_argument('--p2',type=int, default=560,help='limitation')
    parser.add_argument('--p3',type=int, default=607,help='limitation')
    parser.add_argument('--p4',type=int, default=754,help='limitation')`

what those means,

**Comment by thangphung215** [comment]
the result is save in folder 'runs', if you dont have, you need to create it. Those p1 to p4 mean the value of y corresponding to those line on screen to determine the limit of distance to get the speed. You may need to draw the line to see them. Because the idea is each line has distance to next one equal to 8m in real world, so I compute the time of the vehicle spends to cross 2 line and get speed = 8m/time (m/s)

**Comment by thangphung215** [comment]
No man, the --kph is the path to the record of your speedometer pls. If you dont have it, you need to delete the function using it in the code or you need to record another one. The video file of front view and speedometer need to be recorded at the same time. the file hsv_thresh.py is used to get the needle on the speedometer out of the speedometer.

**Comment by VYRION-Ai** [comment]
@thangphung215 no the video didn't saved , but the exp is created and it is empty.
and What do you mean by drawing a line

**Comment by thangphung215** [comment]
@totoadel those lines are drawn in the video on youtube I have posted in the readme will show you the clearly definition about them. And about the save file, I think you need to check your code again because I try and it work normally. Thank you so much

**Comment by VYRION-Ai** [comment]
i try using colab , and video saved successfully , i see now the problem is in my PC.
but the original deep-sort repo is saving video, i don't know where is the problem in my PC,
thank you very much @thangphung215 .

**Comment by VYRION-Ai** [comment]
i close the issue @thangphung215  but 
i need you help, this is a video i am working with 
https://www.dropbox.com/s/g22uejj4omoc0i4/car2.mp4
, i cannot draw the four lines , i change the four point as this

`python track_4.py --source car2.mp4  --save-vid --yolo_model yolov5s.pt --imgsz 460  --classes 2 3 4 5 6 7 --s 10 --p1 100 --p2 140  --p3 120 --p4 230`

now how to draw the four lines , i am sorry if i am bother you

**Comment by thangphung215** [comment]
@totoadel on the line 309, you may draw the line im0 = cv2.line(im0, (x0,y0), (x1,y1), (255,255,0),2) with the x0=0, x1=width of your image, y1=y0=p1 or p2 p3 p4. https://www.geeksforgeeks.org/python-opencv-cv2-line-method/. Try it

**Comment by VYRION-Ai** [comment]
> @totoadel on the line 309, you may draw the line im0 = cv2.line(im0, (x0,y0), (x1,y1), (255,255,0),2) with the x0=0, x1=width of your image, y1=y0=p1 or p2 p3 p4. https://www.geeksforgeeks.org/python-opencv-cv2-line-method/. Try it

Thank you very much @thangphung215 , it works well and also i solve the problem of savings   video to my PC

**Comment by thangphung215** [comment]
> > @totoadel on the line 309, you may draw the line im0 = cv2.line(im0, (x0,y0), (x1,y1), (255,255,0),2) with the x0=0, x1=width of your image, y1=y0=p1 or p2 p3 p4. https://www.geeksforgeeks.org/python-opencv-cv2-line-method/. Try it
> 
> 
> 
> Thank you very much @thangphung215 , it works well and also i solve the problem of savings   video to my PC 

Congratulations

**Comment by 1300218071** [comment]
Hi, @totoadel can you plz share your code with me I am facing exactly the same issue as yours. plz share your updated code with me which you have done without the kph file

**Comment by VYRION-Ai** [comment]
> Hi, @totoadel can you plz share your code with me I am facing exactly the same issue as yours. plz share your updated code with me which you have done without the kph file

@1300218071 i think the last version is working well

Just use this 
`python track_4.py --source car2.mp4 --save-vid --yolo_model yolov5s.pt --imgsz 460 --classes 2 3 4 5 6 7 --s 10 --p1 100 --p2 140 --p3 120 --p4 230`

Now how to decide the four points
Get a frame of your video
 And open paint application and get four points that is  show the same distance on the real world not the same distance on the screen ( the distance between the four points are equal in the real world not equal to the screen)

**Comment by 1300218071** [comment]
@totoadel sorry I did not understand the four points logic part can you help me personally if I send u my video and code via email am facing a lot of trouble. And also when I run the code speed remains 0 only. plz help me

**Comment by VYRION-Ai** [comment]
@1300218071 use this [https://www.dropbox.com/s/ri6zsdtwvs4cpqb/track_4.py?dl=0](this )

`python track_4.py --source cars.mp4  --save-vid --yolo_model yolov5s.pt --imgsz 640 --show-vid --device 0 --classes 2 3 4 5 6 7 --p1 154 --p2 172  --p3 195 --p4 220
`

**Comment by VYRION-Ai** [comment]
@1300218071 and this is the test video use it with the code above [https://www.dropbox.com/s/y7dl59uiyr4nx8v/cam_04.mp4?dl=0](https://www.dropbox.com/s/y7dl59uiyr4nx8v/cam_04.mp4?dl=0)

**Comment by 1300218071** [comment]
@totoadel how do u get p1,p2,p3,p4 and how can i determine this four points for other videoes
