### ISSUE TITLE
this request ,I want to detect one side of the road 

### ISSUE THREAD

**Issue by VYRION-Ai** [thangphung215/Vehicle_detection_tracking_speed_estimation_front_view#2]
@thangphung215 this request ,I want to detect part of video ,like one side of the road

**Comment by thangphung215** [comment]
> @thangphung215 this request ,I want to detect part of video ,like one side of the road

I think if the camera is located, you can limit by drawing lines to get highest accuracy. 
If the camera is moving, you may want to use segmentation.
Thank you

**Comment by VYRION-Ai** [comment]
@thangphung215 , i use located camera, i can draw lines, as you told me before, but i can not understand what is the benefit of that, i have two side road in the video ,  i only want to detect object speed in one side only

**Comment by thangphung215** [comment]
> @thangphung215 , i use located camera, i can draw lines, as you told me before, but i can not understand what is the benefit of that, i have two side road in the video , i only want to detect object speed in one side only

When the bounding boxes are determined, if they are in the area you want to track, let them go, else, continue to the next box. 
Thank you

**Comment by KhalladiSofianeIT** [comment]
How we Can detecte speed on one road ? I have video of two road thanks

**Comment by thangphung215** [comment]
> How we Can detecte speed on one road ? I have video of two road thanks

v = S/t . We determine a distance =>S, track the time the vehicle take to finish that distance =>t  and finish, get the speed v=S/t
Thank you

**Comment by KhalladiSofianeIT** [comment]
Can you send me your email ? I send you video please to try with it

**Comment by thangphung215** [comment]
> Can you send me your email ? I send you video please to try with it

You can send the link of your video here for anyone can help you with many way but not only mine.
Thank you

**Comment by VYRION-Ai** [comment]
> > @thangphung215 , i use located camera, i can draw lines, as you told me before, but i can not understand what is the benefit of that, i have two side road in the video , i only want to detect object speed in one side only
> 
> When the bounding boxes are determined, if they are in the area you want to track, let them go, else, continue to the next box. Thank you

@thangphung215 thank you ,this works for me
